---
- name: Deploy application into EKS cluster
  hosts: appserver
  gather_facts: yes
  become: yes

  tasks:

    - name: Copy Kubernetes deployment file to app server
      copy:
        src: "{{ playbook_dir }}/k8s_deployment.yaml"
        dest: /root/k8s_deployment.yaml
        mode: '0644'

    - name: Check if kubeconfig exists on remote host
      stat:
        path: /root/.kube/config
      register: kubeconfig_stat

    - name: Copy kubeconfig to target if missing
      copy:
        src: "{{ playbook_dir }}/kubeconfig"
        dest: /root/.kube/config
        mode: '0600'
        owner: ec2-user
      when: not kubeconfig_stat.stat.exists

    - name: Apply Kubernetes deployment
      command: kubectl apply -f /root/k8s_deployment.yaml
      environment:
        KUBECONFIG: /root/.kube/config
